version: "3"
services:
    # my-app:
    # image: ${docker-registry}/my-app:1.0
    # ports:
    # - 3000:3000
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
        ports:
            - 8080:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
            - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
    mongo-data:
        driver: local
